project 'CapstoneProject.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CapstoneProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CapstoneProject
  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'Charts'
  pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
  #pod 'ActiveLabel'

end
