project 'CapStoneProject.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CapStoneProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CapStoneProject
  pod 'SVProgressHUD'
  pod 'Alamofire', '~> 4.7.3' 
  pod 'SwiftyJSON', '~> 4.2.0'
  pod 'RxSwift'

end
